### ISSUE TITLE
Diagnóstico de endpoints de DVE en titán

### ISSUE THREAD

**Issue by milo19980525** [udistrital/titan_api_mid#351]
Revisar los endpoints que se encuentran en el api mid de titán en novedadVE.go.

Los endpoints necesarios para calcular la preliquidación para docentes DVE (HCH y HCS) son:

1. Resoluciones de Vinculación
2. Resoluciones de modificación (Reducción y adición)
3. Resoluciones de cancelación

_Nota: Apoyarse en: https://drive.google.com/file/d/1ItmtYbBH2QhmtG6MiyM-8dWPd1X-7AZ7/view?usp=share_link_

**Criterios de aceptación**

- [x] Relacionar que hallazgos fueron encontrados y que falta por desarrollar

**Comment by diagutierrezro** [comment]
https://docs.google.com/spreadsheets/d/1o3pxlwf3csggIpz_bSH1MYm6m7owio4FkkZnv49FQFo/edit#gid=0
