### ISSUE TITLE
Revisión de endpoints y funciones

### ISSUE THREAD

**Issue by milo19980525** [udistrital/titan_api_mid#361]
- [x] Revisar que el cálculo de desagregado se realice correctamente una vez se aplique una novedad.
Revisar funcionamiento de controlador para novedad de adición.
- [x] HCH
- [x] HCS
- [x] Revisar IBC cuando la cantidad de semanas en un mes es diferente a 4.

**Comment by diagutierrezro** [comment]
Se realiza la revisión del calculo del IBC para HCH y HCS sin encontrar problemas.
Para el desagregado despues una novedad parece funcionar correctamente sin embargo por el cambio de vigencia este no se está realizando correctamente en la vigencia 2023
