### ISSUE TITLE
Pruebas funcionales endpoints sin interoperabilidad

### ISSUE THREAD

**Issue by milo19980525** [udistrital/titan_api_mid#366]
Probar los endpoints de:

1. Anulación
2. Vinculación
3. Adición

Lo  anterior teniendo en cuenta casos exhaustivos dónde se evidencie la posible mezcla de novedades sobre docentes DVE como: 

- Vinculación, adición, adición, adición, anulación.
- Vinculación, adición, anulación
- Vinculación, anulación
- Otros que puedan ser incluidos.

**Criterios de aceptación**

- [x] Pruebas funcionales asociadas a casos de contratos DVE y sus diferentes novedades.
- [x] Formato de hallazgos.

**Comment by diagutierrezro** [comment]
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/diagutierrezr_udistrital_edu_co/EaxX3DWmRxZKq7yFR-PZWmYBGTU10ZuBP9T6Wiq8mat_jg?e=N4euIN
