### ISSUE TITLE
Depliegue a producción posterior a hallazgos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/titan_api_mid#368]
Se requiere listar los elementos necesarios para salir a producción con la API mid del sistema, así como registrar la trazabilidad de las solicitudes que se realicen.

**Criterios de aceptación**

- [x]  Checklist de salida a producción por cada API y el cliente.
- [x]  Trazabilidad de peticiones y commits para salida a producción.
- [x]  Estabilización del sistema en producción.

**_**Nota: Tomar como ejemplo los checklist utilizados en resoluciones https://github.com/udistrital/resoluciones_cliente_v2/issues/68**_**

**Comment by diagutierrezro** [comment]
[Checklist para paso a producción](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/Efb4cTa1mYxIvG_cOFUgUwcBuS6Mt0ZTvqnKG5IyMksT8g?e=rudYxP)

**Comment by diagutierrezro** [comment]
Se realiza el respectivo Pull request a producción, el API queda desplegado correctamente y está estabilziado
