### ISSUE TITLE
Desarrollo funcionalidad de reducciones

### ISSUE THREAD

**Issue by milo19980525** [udistrital/titan_api_mid#369]
Implementar Endpoint para liquidar contratos de docentes DVE una vez se expida una resolución de reducción:

- [x] HCH
- [x] HCS

Tener en cuenta los casos:

1. Vinculación y reducción.
2. Vinculación, adición y reducción.
3. Vinculación, adición, adición y reducción.
4. Vinculación adición, adición, adición y reducción.

**Criterios de aceptación**

- [x] Commit
- [x] PR a dev y a pruebas
- [x] Prueba de funcionamiento en pruebas o en ambiente local emulando ambiente de pruebas.

**Comment by diagutierrezro** [comment]
El desarrollo de esta novedad se realiza manejandolo como una anulación de los contratos que se vean afectados por esta reducción y posteriormente creando una nueva preliquidación con los datos que se envían desde resoluciones
