### ISSUE TITLE
Hallazgos Novedades

### ISSUE THREAD

**Issue by milo19980525** [udistrital/titan_api_mid#370]
- [x] Cuando se cuenta con un contrato que se ejecuta en diferentes vigencias, al momento de generar una suspensión, elimina las preliquidaciones hasta la novedad y no los vuelve a crear.

**Comment by diagutierrezro** [comment]
Se realiza la revisión del porque se genera este error, se encuentra que simplemente se debe a un error en los datos que se envían desde el cliente, se hace la revisión con @Yaov05 realizando esta corrección y de esta manera el sistema funciona correctamente.
