### ISSUE TITLE
Hallazgo previo despliegue a producción

### ISSUE THREAD

**Issue by milo19980525** [udistrital/titan_api_mid#373]
- [x] En las anulaciones poner el registro original en false y crear uno nuevo con los datos correspondientes (valor, fecha fin) para que quede la trazabilidad con auditoría.

**Comment by diagutierrezro** [comment]
Se crea un registro nuevo con la información original del contrato y el registro que ya estaba se modifica con la nueva fecha de finalización y el valor del contrato. Para encontrar el nuevo valor del contrato se hizo necesario realizar una consulta de los detalles_preliquidación del contrato despues de eliminar los detalles de los meses en los que no se va a ejecutar el contrato.
