### ISSUE TITLE
Pruebas funcionales del endpoint de reducciones

### ISSUE THREAD

**Issue by milo19980525** [udistrital/titan_api_mid#377]
Realizar pruebas funcionales que permitan evidenciar el comportamiento en titán cuando se desea ejecutar una preliquidación a un docente con novedad de reducción.

**Criterios de aceptación**
Pruebas funcionales documentadas en el documento de hallazgos.

**Comment by diagutierrezro** [comment]
Se realizan pruebas funcionales de la novedad de reducciones donde se evidenciaron los siguientes [hallazgos](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/diagutierrezr_udistrital_edu_co/Ed5iAIs9HjdPiHY8jYnaRpAB8Spm3VDZHlLuJbBHtodDXg?e=hparFO)
