### ISSUE TITLE
Ajuste a funcionalidad de reducciones

### ISSUE THREAD

**Issue by milo19980525** [udistrital/titan_api_mid#379]
Realizar ajuste para reducciones que tienen tiempo exacto de reducción con respecto a adiciones y la vinculación inicial.

**Comment by diagutierrezro** [comment]
Se realiza el ajuste en la novedad de las reducciones cuando estas afectan contratos de tiempo exactos, se modifican los valores a 0 y se ajustan los respectivos contratos generales que se manejan en las DB
