### ISSUE TITLE
Ajuste de reducciones

### ISSUE THREAD

**Issue by milo19980525** [udistrital/titan_api_mid#380]
- [x] Con base en lo acordado con Juan Pablo, ajustar el endpoint de reducciones para que reciba el valor completo de los contratos iniciales que fueron reducidos.
- [x] A partir del valor recibido realizar diferencia de valores de lo pagado con lo adeudado.
- [x] Liquidar las semanas restantes con base en la diferencia calculada.

**Comment by diagutierrezro** [comment]
Se realiza el ajuste del endpoint de la siguiente manera: 
- Teniedo en cuenta que la preliquidación se hace enviandole el valor de la semana y la cantidad de semanas al ruler para registrar los respectivos detalle_preliquidacion se procede a consultar los detalles_preliquidacion del contrato hasta el mes anterior a la reducción para saber el valor de lo liquidado hasta ese momento.
- Se realiza la resta del valor anterior con el valor del contrato reducido que llega desde resoluciones y se calcula con la cantidad de semanas el valor de cada semana para realizar el ajuste.


**NOTA:** Aún no se cierra el issue esperando a realizar las respectivas pruebas directamente con el cliente de resoluciones

**Comment by diagutierrezro** [comment]
Se realizan pruebas de la funcionalidad junto con la interoperabilidad con el cliente de resoluciones V2 y no se evidencian errores
