### ISSUE TITLE
Ajustar adición de novedades

### ISSUE THREAD

**Issue by milo19980525** [udistrital/titan_api_mid#382]
- [x] Ajustar la adición de novedades en los casos en los que las cuotas indicadas superan los meses restantes del contrato

**Comment by diagutierrezro** [comment]
Se realiza el ajuste para las novedades de los contratos: Por solicitud de @corio27  cuando se agrega una novedad a un contrato por un determinado tiempo estas se aplican por los meses disponibles en el contrato:
Ej: A un contrato le quedan 3 meses pero le agregan una novedad por 5, solo se agregará esta novedad los 3 meses restantes y los otros 2 se ignoran.

El cambio ya se encuentra en [producción](https://github.com/udistrital/titan_api_mid/pull/384)
