### ISSUE TITLE
Ajustar pagos de aportes mensuales

### ISSUE THREAD

**Issue by milo19980525** [udistrital/titan_api_mid#403]
Se requiere cajustar pagos de aportes mensuales para doble contratación cuando el ibc de uno de los contratos es menor al ibc minimo.

**Especificaciones técnicas**

- El desarrollo actual se encuentra en producción, por lo que debe ser tipo Hotfix la corrección.

**Sub Tareas**

- [x] Revisar porque se presenta el error.
- [x] Corrección de errores o bugs encontrados.
- [x] Pruebas de corrección de errores.

**Criterios de aceptación**

- [x] Los errores que presenta la api se encuentran detectados y corregidos.
- [x] La Api se encuentra desplegada en pruebas y producción.

**Requerimientos**

- [x] Las funcionalidades se encuentran en release

**Dependencias**

- Ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] PR a Master.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
No se realiza PR a develop ni release ya que es un hotfix directo a producción
