### ISSUE TITLE
Servicio para consultar resumen de pago de contrato de docente hora cátedra salarios

### ISSUE THREAD

**Issue by mariaortiz0401** [udistrital/titan_api_mid#54]
Se solicita que, dado un profesor, un valor de contrato, una fecha de inicio y fin del mismo y su vigencia, se devuelva el valor por concepto de los pagos que se le realizarán al docente. Por el momento, estos conceptos son:

1. Salario básico para el total de la vinculación
2. Prima de vacaciones
3. Vacaciones
4. Prima de servicios
5. Cesantías
6. Intereses de censantías

**Comment by mariaalejandra9404** [comment]
El servicio cuyo endpoint es /v1/services/desagregacion_contrato_hcs se le debe enviar el siguiente JSON por medio de un post

``` JSON
{
 	"NumDocumento": 12321,
 	"ValorTotalContrato": 22359132,
 	"VigenciaContrato": 2019
}
```

Eĺ va a retornar la siguiente información, donde los campos a consultar serán *AliasConcepto* y *Valor* 

``` JSON
[
    {
        "Id": 0,
        "Nombre": "salarioBase",
        "Base": "",
        "Valor": "17882009",
        "DiasLiquidados": "",
        "TipoPreliquidacion": "",
        "NaturalezaConcepto": 0,
        "AliasConcepto": "'Sueldo Basico'",
        "IdPersona": 0
    },
    {
        "Id": 0,
        "Nombre": "vacaciones",
        "Base": "0",
        "Valor": "741770",
        "DiasLiquidados": "",
        "TipoPreliquidacion": "",
        "NaturalezaConcepto": 0,
        "AliasConcepto": "'Vacaciones'",
        "IdPersona": 0
    },
    {
        "Id": 0,
        "Nombre": "primaVacaciones",
        "Base": "0",
        "Valor": "741770",
        "DiasLiquidados": "",
        "TipoPreliquidacion": "",
        "NaturalezaConcepto": 0,
        "AliasConcepto": "'Prima De Vacaciones'",
        "IdPersona": 0
    },
    {
        "Id": 0,
        "Nombre": "primaNavidad",
        "Base": "0",
        "Valor": "1324593",
        "DiasLiquidados": "",
        "TipoPreliquidacion": "",
        "NaturalezaConcepto": 0,
        "AliasConcepto": "'Prima De Navidad'",
        "IdPersona": 0
    },
    {
        "Id": 0,
        "Nombre": "cesantias",
        "Base": "0",
        "Valor": "1490166",
        "DiasLiquidados": "",
        "TipoPreliquidacion": "",
        "NaturalezaConcepto": 0,
        "AliasConcepto": "'Censantías'",
        "IdPersona": 0
    },
    {
        "Id": 0,
        "Nombre": "interesCesantias",
        "Base": "0",
        "Valor": "178824",
        "DiasLiquidados": "",
        "TipoPreliquidacion": "",
        "NaturalezaConcepto": 0,
        "AliasConcepto": "'Intereses De Cesantias'",
        "IdPersona": 0
    }
]
```

**Comment by BrayanB24** [comment]
Analizando la respuesta del servicio se tienen algunas dudas sobre unos elementos. El primero es que hace falta el concepto de "Prima de Servicios" el cual queda pendiente de implementación hasta cuando se obtenga la ecuación que debería ir en el ruler para calcularlo; El segundo es que no aparece con claridad el concepto de "Aportes de Cesantías a Fondos Públicos", en su lugar hay dos parámetros ("Intereses de Cesantías" y "Cesantías") que hay que evaluar si son lo mismo o se debe modificar.

**Comment by mariaalejandra9404** [comment]
Se publica servicio en producción. Para acceder a él, la URL es: http://api.intranetoas.udistrital.edu.co:8082/v1/services/desagregacion_contrato_hcs 

Es un servicio POST que requiere como parámetro un JSON:

```JSON
{
 	"NumDocumento": 12321,
 	"ValorTotalContrato": 22359132,
 	"VigenciaContrato": 2019
}
```

**Comment by BrayanB24** [comment]
Se revisa el servicio publicado en producción y funciona de manera correcta, se realizarán los ajustes necesarios en el cliente para que se haga uso del mismo.
